#!/bin/sh /etc/rc.common
# Copyright (C) 2023 Tianling Shen <cnsztl@immortalwrt.org>

USE_PROCD=0
START=98

CONF="daed"
PROG="/usr/bin/daed"
LOG="/var/log/daed/daed.log"
CRON_FILE="/etc/crontabs/root"
RANDOM_SEED=$RANDOM
RANDOM_NUM=$((RANDOM_SEED % 10 + 1))

setcron() {
  touch $CRON_FILE
  sed -i '/daed_sub.sh/d' $CRON_FILE 2>/dev/null
  [ "$(uci -q get daed.config.subscribe_auto_update)" -eq 1 ] && echo "${RANDOM_NUM} $(uci -q get daed.config.subscribe_update_day_time) * * $(uci -q get daed.config.subscribe_update_week_time) /etc/daed/daed_sub.sh >/dev/null 2>&1" >>$CRON_FILE
  crontab $CRON_FILE
}

delcron() {
  sed -i '/daed_sub.sh/d' $CRON_FILE 2>/dev/null
  crontab $CRON_FILE
}

setlocaluse() {
  uci set dhcp.@dnsmasq[0].localuse="1"
  uci commit dhcp
  /etc/init.d/dnsmasq restart
}

dellocaluse() {
  uci set dhcp.@dnsmasq[0].localuse="0"
  uci commit dhcp
  /etc/init.d/dnsmasq restart
  . /lib/functions/network.sh
  network_find_wan LOGICAL_WAN || exit 1
  dns_list=$(ubus call network.interface.$LOGICAL_WAN status | jsonfilter -e '@["dns-server"]' | sed 's/[]["]//g' | sed 's/,/\n/g' | grep -oE '\b([0-9]{1,3}\.){3}[0-9]{1,3}\b')
  [ -z "$dns_list" ] && dns_list="119.29.29.29 180.76.76.76 223.5.5.5"
  grep -v '^nameserver ' /etc/resolv.conf > /tmp/resolv.conf.new.daed 2>/dev/null
  for dns in $dns_list; do
    echo "nameserver $dns" >> /tmp/resolv.conf.new.daed
  done
  cat /tmp/resolv.conf.new.daed > /etc/resolv.conf
  rm -f /tmp/resolv.conf.new.daed
}

start_service() {
  [ -f "/etc/init.d/daed" ] && grep -q "DAE_LOCATION_ASSET" "/etc/init.d/daed" || sed -i '/run/i\  procd_set_param env DAE_LOCATION_ASSET="/usr/share/v2ray"' "/etc/init.d/daed"
  config_load "$CONF"

  local enabled
  config_get_bool enabled "config" "enabled" "0"
  if [ "$enabled" -eq 0 ]; then
    #delcron
    setlocaluse
    return 1
  fi
  #setcron
  dellocaluse
}

stop_service() {
  #delcron
  setlocaluse
}

service_triggers() {
  procd_add_reload_trigger "$CONF"
}
