#!/bin/sh
[ "${ACTION}" = "ifup" ] && {
    LOCK_FILE="/tmp/lock/daed_hotplug_lock"
    if mkdir "$LOCK_FILE" 2>/dev/null; then
        trap 'rmdir "$LOCK_FILE"' EXIT
        sleep 10
        DEVICE=$(logread | grep "link is up" | tail -n 1 | awk -F "'" '{print $2}')
        DEVICE_TYPE=$(ip link show dev "$DEVICE")
        if [[ "$DEVICE_TYPE" == *"link/ether"* ]]; then
            /etc/init.d/daed restart
        else
            exit 1
        fi 
    else
        exit 1
    fi
}
