#!/bin/sh /etc/rc.common
# Copyright (C) 2023 Tianling Shen <cnsztl@immortalwrt.org>

START=99

CONF="daed"
PROG="/usr/bin/daed"
LOG="/var/log/daed/daed.log"
CRON_FILE="/etc/crontabs/root"

setcron() {
  touch $CRON_FILE
  sed -i '/daed_sub.sh/d' $CRON_FILE 2>/dev/null
  [ "$(uci -q get daed.config.subscribe_auto_update)" -eq 1 ] && echo "0 $(uci -q get daed.config.subscribe_update_day_time) * * $(uci -q get daed.config.subscribe_update_week_time) /etc/daed/daed_sub.sh" >>$CRON_FILE
  crontab $CRON_FILE
}

delcron() {
  sed -i '/daed_sub.sh/d' $CRON_FILE 2>/dev/null
  crontab $CRON_FILE
}

start_service() {
  config_load "$CONF"

  local enabled
  config_get_bool enabled "config" "enabled" "0"
  if [ "$enabled" -eq 0 ]; then
    delcron
    return 1
  fi
  setcron
}

stop_service() {
  delcron
}

service_triggers() {
  procd_add_reload_trigger "$CONF"
}
